version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app

  tests:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: npm run test
